services:
  postgres:
    image: postgres:17-alpine
    container_name: khmer_sign_postgres
    environment:
      TZ: Asia/Phnom_Penh
      PGTZ: Asia/Phnom_Penh
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: khmer_sign_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "timezone=Asia/Phnom_Penh"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d khmer_sign_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - khmer_network

  redis:
    image: redis:7-alpine
    container_name: khmer_sign_redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - khmer_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: khmer_sign_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - khmer_network
  
volumes:
  postgres_data:
  redis_data:

networks:
  khmer_network:
    driver: bridge
