"""Admin content-management schemas (shared across learning tracks)."""

from .analytics import (
    DashboardAnalyticsResponse,
    FeedbackDistribution,
    KpiValue,
    LeaderboardEntry,
    LearningProgressDonut,
    LessonDifficultyEntry,
    LessonRankEntry,
    MonthlyActiveUsers,
    OverviewStats,
    TrackCompletionStats,
    TrackProgress,
)
from .curriculum import (
    ChapterCreate,
    ChapterResponse,
    ChapterUpdate,
    LessonCreate,
    LessonResponse,
    LessonUpdate,
    UnitCreate,
    UnitResponse,
    UnitUpdate,
)
from .exercise import (
    ExerciseCreate,
    ExerciseOptionCreate,
    ExerciseOptionResponse,
    ExerciseOptionUpdate,
    ExerciseResponse,
    ExerciseUpdate,
)

__all__ = [
    "DashboardAnalyticsResponse",
    "FeedbackDistribution",
    "KpiValue",
    "LeaderboardEntry",
    "LearningProgressDonut",
    "LessonDifficultyEntry",
    "LessonRankEntry",
    "MonthlyActiveUsers",
    "OverviewStats",
    "TrackCompletionStats",
    "TrackProgress",
    "UnitCreate",
    "UnitUpdate",
    "UnitResponse",
    "ChapterCreate",
    "ChapterUpdate",
    "ChapterResponse",
    "LessonCreate",
    "LessonUpdate",
    "LessonResponse",
    "ExerciseCreate",
    "ExerciseUpdate",
    "ExerciseResponse",
    "ExerciseOptionCreate",
    "ExerciseOptionUpdate",
    "ExerciseOptionResponse",
]
