"""add sentence spelling tables

Revision ID: 7c76dbdfc0d8
Revises: c8e1a3f5b7d9
Create Date: 2026-09-11 11:17:27.915906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c76dbdfc0d8'
down_revision: Union[str, None] = 'c8e1a3f5b7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_spelling_sentences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text_kh', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_kh', name='uq_sentence_spelling_sentences_text_kh')
    )
    op.create_table('sentence_spelling_practice_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('sample', 'custom', name='sentence_spelling_source'), nullable=False),
    sa.Column('sentence_id', sa.BigInteger(), nullable=True),
    sa.Column('practiced_text', sa.Text(), nullable=False),
    sa.Column('character_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('accuracy_percent', sa.Float(), server_default='0', nullable=False),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence_spelling_sentences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sentence_spelling_practice_attempts_sentence_id', 'sentence_spelling_practice_attempts', ['sentence_id'], unique=False)
    op.create_index('ix_sentence_spelling_practice_attempts_user_completed', 'sentence_spelling_practice_attempts', ['user_id', 'completed_at'], unique=False)
    op.create_index('ix_sentence_spelling_practice_attempts_user_id', 'sentence_spelling_practice_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentence_spelling_practice_attempts_user_id', table_name='sentence_spelling_practice_attempts')
    op.drop_index('ix_sentence_spelling_practice_attempts_user_completed', table_name='sentence_spelling_practice_attempts')
    op.drop_index('ix_sentence_spelling_practice_attempts_sentence_id', table_name='sentence_spelling_practice_attempts')
    op.drop_table('sentence_spelling_practice_attempts')
    op.drop_table('sentence_spelling_sentences')
    op.execute("DROP TYPE IF EXISTS sentence_spelling_source")
    # ### end Alembic commands ###
