"""add finger spelling tables

Revision ID: d2598ebc2622
Revises: 91a7e1c9c841
Create Date: 2026-05-28 11:19:32.378959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2598ebc2622'
down_revision: Union[str, None] = '91a7e1c9c841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finger_letters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('letter_en', sa.String(length=100), nullable=True),
    sa.Column('letter_kh', sa.String(length=100), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_kh', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('letter_kh', name='uq_finger_letters_letter_kh')
    )
    op.create_table('finger_units',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_kh', sa.String(length=255), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_kh', sa.Text(), nullable=True),
    sa.Column('order_index', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_kh', name='uq_finger_units_name_kh'),
    sa.UniqueConstraint('order_index', name='uq_finger_units_order_index')
    )
    op.create_index('ix_finger_units_order_index', 'finger_units', ['order_index'], unique=False)
    op.create_table('medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('video', 'gif', 'image', name='media_type'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finger_chapters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_kh', sa.String(length=255), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_kh', sa.Text(), nullable=True),
    sa.Column('order_index', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['finger_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'order_index', name='uq_finger_chapters_unit_id_order_index')
    )
    op.create_index('ix_finger_chapters_order_index', 'finger_chapters', ['order_index'], unique=False)
    op.create_index('ix_finger_chapters_unit_id', 'finger_chapters', ['unit_id'], unique=False)
    op.create_table('finger_letter_medias',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('letter_id', sa.BigInteger(), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['letter_id'], ['finger_letters.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finger_letter_medias_letter_id', 'finger_letter_medias', ['letter_id'], unique=False)
    op.create_index('ix_finger_letter_medias_media_id', 'finger_letter_medias', ['media_id'], unique=False)
    op.create_table('finger_lessons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chapter_id', sa.BigInteger(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_kh', sa.String(length=255), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_kh', sa.Text(), nullable=True),
    sa.Column('order_index', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['finger_chapters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'order_index', name='uq_finger_lessons_chapter_id_order_index')
    )
    op.create_index('ix_finger_lessons_chapter_id', 'finger_lessons', ['chapter_id'], unique=False)
    op.create_index('ix_finger_lessons_order_index', 'finger_lessons', ['order_index'], unique=False)
    op.create_table('finger_exercises',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('question_en', sa.Text(), nullable=False),
    sa.Column('question_kh', sa.Text(), nullable=False),
    sa.Column('exercise_type', sa.Enum('MULTIPLE_CHOICE', 'FREE_FORM', 'IMAGE_SELECT', 'MATCHING', name='finger_exercise_type'), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('explanation_kh', sa.Text(), nullable=True),
    sa.Column('order_index', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['finger_lessons.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'order_index', name='uq_finger_exercises_lesson_order')
    )
    op.create_index('ix_finger_exercises_lesson_id', 'finger_exercises', ['lesson_id'], unique=False)
    op.create_index('ix_finger_exercises_media_id', 'finger_exercises', ['media_id'], unique=False)
    op.create_index('ix_finger_exercises_order_index', 'finger_exercises', ['order_index'], unique=False)
    op.create_table('finger_lesson_letters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('letter_id', sa.BigInteger(), nullable=False),
    sa.Column('order_index', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['finger_lessons.id'], ),
    sa.ForeignKeyConstraint(['letter_id'], ['finger_letters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'letter_id', name='uq_finger_lesson_letters_lesson_letter'),
    sa.UniqueConstraint('lesson_id', 'order_index', name='uq_finger_lesson_letters_lesson_order')
    )
    op.create_index('ix_finger_lesson_letters_lesson_id', 'finger_lesson_letters', ['lesson_id'], unique=False)
    op.create_index('ix_finger_lesson_letters_letter_id', 'finger_lesson_letters', ['letter_id'], unique=False)
    op.create_index('ix_finger_lesson_letters_order_index', 'finger_lesson_letters', ['order_index'], unique=False)
    op.create_table('finger_practice_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.BigInteger(), nullable=False),
    sa.Column('average_accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('peak_accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['finger_lessons.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finger_practice_sessions_lesson_id', 'finger_practice_sessions', ['lesson_id'], unique=False)
    op.create_index('ix_finger_practice_sessions_media_id', 'finger_practice_sessions', ['media_id'], unique=False)
    op.create_index('ix_finger_practice_sessions_user_id', 'finger_practice_sessions', ['user_id'], unique=False)
    op.create_table('finger_user_lesson_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('finger_lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('peak_accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('attempts', sa.BigInteger(), nullable=False),
    sa.Column('total_time_spent', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finger_lesson_id'], ['finger_lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'finger_lesson_id', name='uq_finger_user_lesson_progress_user_lesson')
    )
    op.create_index('ix_finger_user_lesson_progress_lesson_id', 'finger_user_lesson_progress', ['finger_lesson_id'], unique=False)
    op.create_index('ix_finger_user_lesson_progress_user_id', 'finger_user_lesson_progress', ['user_id'], unique=False)
    op.create_table('finger_exercise_options',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('option_text_en', sa.String(length=500), nullable=True),
    sa.Column('option_text_kh', sa.String(length=500), nullable=True),
    sa.Column('media_id', sa.BigInteger(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('points', sa.BigInteger(), nullable=False),
    sa.Column('order_index', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['finger_exercises.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'order_index', name='uq_finger_exercise_options_exercise_order')
    )
    op.create_index('ix_finger_exercise_options_exercise_id', 'finger_exercise_options', ['exercise_id'], unique=False)
    op.create_index('ix_finger_exercise_options_media_id', 'finger_exercise_options', ['media_id'], unique=False)
    op.create_index('ix_finger_exercise_options_order_index', 'finger_exercise_options', ['order_index'], unique=False)
    op.create_table('finger_practice_session_letters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('letter_id', sa.BigInteger(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('attempts', sa.BigInteger(), nullable=False),
    sa.Column('time_spent_seconds', sa.BigInteger(), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['letter_id'], ['finger_letters.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['finger_practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finger_practice_session_letters_letter_id', 'finger_practice_session_letters', ['letter_id'], unique=False)
    op.create_index('ix_finger_practice_session_letters_media_id', 'finger_practice_session_letters', ['media_id'], unique=False)
    op.create_index('ix_finger_practice_session_letters_session_id', 'finger_practice_session_letters', ['session_id'], unique=False)
    op.create_table('finger_user_exercise_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('finger_exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('progress_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.BigInteger(), nullable=True),
    sa.Column('selected_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('time_taken', sa.BigInteger(), nullable=False),
    sa.Column('attempt_number', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finger_exercise_id'], ['finger_exercises.id'], ),
    sa.ForeignKeyConstraint(['progress_id'], ['finger_user_lesson_progress.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['finger_exercise_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finger_user_exercise_results_exercise_id', 'finger_user_exercise_results', ['finger_exercise_id'], unique=False)
    op.create_index('ix_finger_user_exercise_results_progress_id', 'finger_user_exercise_results', ['progress_id'], unique=False)
    op.create_index('ix_finger_user_exercise_results_user_id', 'finger_user_exercise_results', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_finger_user_exercise_results_user_id', table_name='finger_user_exercise_results')
    op.drop_index('ix_finger_user_exercise_results_progress_id', table_name='finger_user_exercise_results')
    op.drop_index('ix_finger_user_exercise_results_exercise_id', table_name='finger_user_exercise_results')
    op.drop_table('finger_user_exercise_results')
    op.drop_index('ix_finger_practice_session_letters_session_id', table_name='finger_practice_session_letters')
    op.drop_index('ix_finger_practice_session_letters_media_id', table_name='finger_practice_session_letters')
    op.drop_index('ix_finger_practice_session_letters_letter_id', table_name='finger_practice_session_letters')
    op.drop_table('finger_practice_session_letters')
    op.drop_index('ix_finger_exercise_options_order_index', table_name='finger_exercise_options')
    op.drop_index('ix_finger_exercise_options_media_id', table_name='finger_exercise_options')
    op.drop_index('ix_finger_exercise_options_exercise_id', table_name='finger_exercise_options')
    op.drop_table('finger_exercise_options')
    op.drop_index('ix_finger_user_lesson_progress_user_id', table_name='finger_user_lesson_progress')
    op.drop_index('ix_finger_user_lesson_progress_lesson_id', table_name='finger_user_lesson_progress')
    op.drop_table('finger_user_lesson_progress')
    op.drop_index('ix_finger_practice_sessions_user_id', table_name='finger_practice_sessions')
    op.drop_index('ix_finger_practice_sessions_media_id', table_name='finger_practice_sessions')
    op.drop_index('ix_finger_practice_sessions_lesson_id', table_name='finger_practice_sessions')
    op.drop_table('finger_practice_sessions')
    op.drop_index('ix_finger_lesson_letters_order_index', table_name='finger_lesson_letters')
    op.drop_index('ix_finger_lesson_letters_letter_id', table_name='finger_lesson_letters')
    op.drop_index('ix_finger_lesson_letters_lesson_id', table_name='finger_lesson_letters')
    op.drop_table('finger_lesson_letters')
    op.drop_index('ix_finger_exercises_order_index', table_name='finger_exercises')
    op.drop_index('ix_finger_exercises_media_id', table_name='finger_exercises')
    op.drop_index('ix_finger_exercises_lesson_id', table_name='finger_exercises')
    op.drop_table('finger_exercises')
    op.drop_index('ix_finger_lessons_order_index', table_name='finger_lessons')
    op.drop_index('ix_finger_lessons_chapter_id', table_name='finger_lessons')
    op.drop_table('finger_lessons')
    op.drop_index('ix_finger_letter_medias_media_id', table_name='finger_letter_medias')
    op.drop_index('ix_finger_letter_medias_letter_id', table_name='finger_letter_medias')
    op.drop_table('finger_letter_medias')
    op.drop_index('ix_finger_chapters_unit_id', table_name='finger_chapters')
    op.drop_index('ix_finger_chapters_order_index', table_name='finger_chapters')
    op.drop_table('finger_chapters')
    op.drop_table('medias')
    op.drop_index('ix_finger_units_order_index', table_name='finger_units')
    op.drop_table('finger_units')
    op.drop_table('finger_letters')
    # ### end Alembic commands ###
