"""remove_total_time_spent_and_started_at

Revision ID: d6ca71e6d712
Revises: 3b1b0c9d5f7a
Create Date: 2026-06-28 17:56:35.550268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6ca71e6d712'
down_revision: Union[str, None] = '3b1b0c9d5f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_finger_practice_session_letters_letter_id', table_name='finger_practice_session_letters')
    op.drop_index('ix_finger_practice_session_letters_media_id', table_name='finger_practice_session_letters')
    op.drop_index('ix_finger_practice_session_letters_session_id', table_name='finger_practice_session_letters')
    op.drop_table('finger_practice_session_letters')
    op.drop_index('ix_finger_practice_sessions_lesson_id', table_name='finger_practice_sessions')
    op.drop_index('ix_finger_practice_sessions_media_id', table_name='finger_practice_sessions')
    op.drop_index('ix_finger_practice_sessions_user_id', table_name='finger_practice_sessions')
    op.drop_table('finger_practice_sessions')
    op.add_column('finger_user_lesson_progress', sa.Column('last_practiced_at', sa.DateTime(), nullable=True))
    op.drop_column('finger_user_lesson_progress', 'peak_accuracy')
    op.drop_column('finger_user_lesson_progress', 'last_accessed_at')
    op.drop_column('finger_user_lesson_progress', 'total_time_spent')
    op.drop_column('finger_user_lesson_progress', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finger_user_lesson_progress', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('finger_user_lesson_progress', sa.Column('total_time_spent', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('finger_user_lesson_progress', sa.Column('last_accessed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('finger_user_lesson_progress', sa.Column('peak_accuracy', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_column('finger_user_lesson_progress', 'last_practiced_at')
    op.create_table('finger_practice_sessions',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('finger_practice_sessions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('average_accuracy', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('peak_accuracy', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['finger_lessons.id'], name='finger_practice_sessions_lesson_id_fkey'),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], name='finger_practice_sessions_media_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='finger_practice_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='finger_practice_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_finger_practice_sessions_user_id', 'finger_practice_sessions', ['user_id'], unique=False)
    op.create_index('ix_finger_practice_sessions_media_id', 'finger_practice_sessions', ['media_id'], unique=False)
    op.create_index('ix_finger_practice_sessions_lesson_id', 'finger_practice_sessions', ['lesson_id'], unique=False)
    op.create_table('finger_practice_session_letters',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('letter_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('accuracy', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('time_spent_seconds', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['letter_id'], ['finger_letters.id'], name='finger_practice_session_letters_letter_id_fkey'),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], name='finger_practice_session_letters_media_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['finger_practice_sessions.id'], name='finger_practice_session_letters_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='finger_practice_session_letters_pkey')
    )
    op.create_index('ix_finger_practice_session_letters_session_id', 'finger_practice_session_letters', ['session_id'], unique=False)
    op.create_index('ix_finger_practice_session_letters_media_id', 'finger_practice_session_letters', ['media_id'], unique=False)
    op.create_index('ix_finger_practice_session_letters_letter_id', 'finger_practice_session_letters', ['letter_id'], unique=False)
    # ### end Alembic commands ###
