"""Change default lesson lock status to true

Revision ID: dfc09d8a49b6
Revises: d2598ebc2622
Create Date: 2026-05-29 12:53:36.954455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc09d8a49b6'
down_revision: Union[str, None] = 'd2598ebc2622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_oauth_providers_user_id', table_name='user_oauth_providers')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_user_oauth_providers_user_id', 'user_oauth_providers', ['user_id'], unique=False)
    # ### end Alembic commands ###
